backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\bootstrap\ActiveForm;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'balance', 'admin-email', 'captcha'],
                'rules' => [
                    [
                        'actions' => ['signup', 'captcha'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'balance', 'admin-email'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                //'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    /**
     * Displays balance page.
     *
     * @return mixed
     */
    public function actionBalance()
    {
        return $this->render('balance');
    }    

    /**
     * Displays admin-mail page.
     *
     * @return mixed
     */
    public function actionAdminEmail()
    {
        return $this->render('admin-email');
    }    

    public function actionSignupvalidate(){
        $model = new SignupForm();
        
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }        
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
                
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/admin-email.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Связь с администрацией';
?>
<div class="main-box main-custom change admin-mail">
    <div class="container">
        <form action="" class="form text-left">
            <textarea type="text" class="form-control message" name="" rows="8" placeholder="Cообщение"></textarea>
            <a href="#" class="page-button save-btn save">Отправить</a>
        </form>
    </div>
</div>
<!-- END main-box -->

frontend/views/site/balance.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Пополнить баланс';

?>
    <div class="main-box main-custom balance ">
        <div class="container text-left" style="padding: 0 10px">
            <div class="balance-title">
                Webmoney <img src="/img/balance/webmoney.png" height="32" width="48" alt="">
            </div>
            
            <p> Создав электронный кошелек Webmoney, Вы сможете не только удобно, но и выгодно пополнять свой счет, комиссия Webmoney составляет всего 0,8%. <a href="">Зарегестирироваться.</a></p>

            <p>Если у Вас уже есть кошелек Webmoney, введите необходимую сумму,  выберите валюту для пополнения счета и нажмите <b>“Пополнить счет”</b></p>
            <form action="">
                <div class="form-group">
                    <input type="text" placeholder="Сумма">
                    <i class="fa fa-money"></i>
                </div>
                <div class="form-group">
                    <select class="selectpicker" title="Валюта">
                        <option data-content="<span class='option'>WMR</span>"></option>
                        <option data-content="<span class='option'>WMZ</span>"></option>
                    </select>
                </div>
                <span class="balance-item">=</span>
                <div class="form-group">
                    <input type="text" placeholder="100 монет" class="money">
                </div>
                <button type="submit" class="page-button">Пополнить счет</button>
            </form>

            <div class="balance-title">Банковская карта <img src="/img/balance/master-card.png" alt=""> <img src="/img/balance/visa.png" alt=""></div>
            
            <p>После нажатия кнопки “Пополнить счет” Вы будете перенаправлены на страницу, защищенную SSL сертификатом, который обеспечивает надежную защииту всех передаваемых данных. Все введенные на этой странице данные строго конфиденциальны, и ни при каких обстоятельствах не могут стать доступны третьим лицам. При первом пополнении банковской картой Вам понадобится ввести данные по картре (номер, имя пользователя и т.д.) Для последующих пополнений достаточно будет лишь указать последние 6 цифр номера карты.</p>
            
            <p>Выберите сумму поплнения и нажмите <b>“Пополнить счет”</b></p>

            <form action="">
                <div class="form-group">
                    <input type="text" placeholder="Сумма">
                    <i class="fa fa-money"></i>
                </div>
                <span class="balance-item">=</span>
                <div class="form-group">
                    <input type="text" placeholder="100 монет" class="money">
                </div>
                <button type="submit" class="page-button">Пополнить счет</button>
                <p>Для обеспечения безопасности при первом пополнении счета с карты, монеты на Ваш счет будут начислены с задержкой 10-15 минут, это время необходимо нам для проверки карты. Все последующие пополнения Вы сможете проводить без ограничений. Эта мера введена в целях защиты от мошенничества, просим отнестись с пониманием.</p>
            </form>

            <div class="balance-title">Яндекс.Деньги, QIWI и другие способы <img src="/img/balance/yad.png" alt=""> <img src="/img/balance/qiwi.png" alt=""></div>

            <p>Пополнение через платежную систему Oplata.info<br>
            После нажатия кнопки “Пополнить счет” Вы будете перенаправлены на страницу платежной системы Oplata.info. Этот платежный сервис предлагает множество альтернативных вариантов оплаты. После завершения операции оплаты Вы будете перенаправлены на страницу своего аккаунта на нашем сайте</p>

            <p>Выберите вариаеи оплаты, сумму поплнения и нажмите “Пополнить счет”</p>

            <form action="">
                <div class="form-group ya-form" style="width: 284px">
                    <select class="selectpicker" title="Яндекс деньги">
                        <option data-content="<span class='option'>Яндекс деньги</span>"></option>
                        <option data-content="<span class='option'>Яндекс деньги</span>"></option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Сумма">
                    <i class="fa fa-money"></i>
                </div>

                <span class="balance-item">=</span>
                <div class="form-group">
                    <input type="text" placeholder="" class="money">
                </div>
                <button type="submit" class="page-button">Пополнить счет</button>
            </form>

            <div class="balance-title">Мобильный телефон <img src="/img/balance/mobile.png" alt=""></div>
            <p>Оплата со счета Вашего мобильного телефона</p>
            <p>Выберите страну и оператора</p>

            <form action="" class="noborder">
                <div class="form-group mobile">
                    <select class="selectpicker" title="Ru - Россия">
                        <option data-content="<span class='option'>Ru - Россия</span>"></option>
                        <option data-content="<span class='option'>En - English</span>"></option>
                    </select>
                </div>
                <div class="form-group mobile">
                    <select class="selectpicker" title="Билайн">
                        <option data-content="<span class='option'>Билайн</span>"></option>
                        <option data-content="<span class='option'>Мегафон</span>"></option>
                    </select>
                </div>
                <p>Если  Вы выбраль этот способ оплаты, убедитесь, что на счете Вашего телефона есть необходимая сумма. После нажатия кнопки “Пополнить счет” Вы получите SMS с запросом подтверждения оплаты. Для подтверждения Вам понадобится отправить ответное SMS с любым текстом. После этого вас счет моментально будет пополнен.</p>

                <p>Ввелите номер своего мобильного телефона в формате 79ххххххххх</p>

                <div class="form-group phone" style="width: 284px">
                    <input type="text" placeholder="Мобильный телефон">
                    <i class="fa fa-mobile"></i>
                </div>

                <p>Введите сумму пополнения и нажмите <b>“Пополнить счет”</b></p>

                <div class="form-group">
                    <input type="text" placeholder="Сумма" class="">
                    <i class="fa fa-money"></i>
                </div>
                <span class="balance-item">=</span>
                <div class="form-group">
                    <input type="text" class="money" placeholder="100 монет">
                </div>
                <button type="submit" class="page-button">Пополнить счет</button>
            </form>

        </div>
    </div>
    <!-- END main-box -->

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <p>
        Ooooops, somethink gone wrong. May be you want to sleep all night, my dear?
    </p>
</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Главная Sosedi';

?>

Главная

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Войти';
?>
<div class="header-title">
    <div class="vertical-center">
        ВХОД
    </div>
</div>

    <div class="main-box main-custom" style="min-height: calc(100% - 237px);">
        <div class="container text-center">
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'options' => ['class' => 'form'], 'fieldConfig' => ['template' => '{input}']]); ?>

                <?= $form
                    ->field($model, 'username', ['template' => '{error}{input}<i class="fa fa-user"></i>'])
                    ->textInput(['placeholder' => "Никнейм"])
                    ->error(['tag'=>'div'])?>
                    
                <?= $form
                    ->field($model, 'password', ['template' => '{error}{input}<i class="fa fa-lock"></i>'])
                    ->passwordInput(['placeholder' => "Пароль"])
                    ->error(['tag'=>'div'])?>

                <ul class="text-left check-wrapper">
                    <li>
                        <?= Html::a('Напомнить пароль', ['site/request-password-reset'], ['class' => 'page-link pull-right']) ?>
                        
                        <?= $form
                            ->field($model, 'rememberMe', ['options'=> ['wrapper'=>false]])
                            ->checkbox(['template'=>'{input}{beginLabel}{labelTitle}{endLabel}'])
                        ?>
                    </li>
                    <li class="empty"></li>
                </ul>
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

frontend/views/site/memberreg.php
<?php
/**
 * Created by PhpStorm.
 * User: whisper
 * Date: 22.04.16
 * Time: 13:02
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Member */
/* @var $form ActiveForm */
?>
<div class="member-register">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'family') ?>
    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'age') ?>
    <?= $form->field($model, 'nationality') ?>
    <?= $form->field($model, 'passport') ?>
    <?= $form->field($model, 'passport_date') ?>
    <?= $form->field($model, 'surname') ?>
    <?= $form->field($model, 'bithday') ?>
    <?= $form->field($model, 'birthplace') ?>
    <?= $form->field($model, 'country') ?>
    <?= $form->field($model, 'city') ?>
    <?= $form->field($model, 'education') ?>
    <?= $form->field($model, 'education_last') ?>
    <?= $form->field($model, 'profession') ?>
    <?= $form->field($model, 'workplace') ?>
    <?= $form->field($model, 'position') ?>
    <?= $form->field($model, 'family_status') ?>
    <?= $form->field($model, 'child') ?>
    <?= $form->field($model, 'talants') ?>
    <?= $form->field($model, 'habbits') ?>
    <?= $form->field($model, 'advantages') ?>
    <?= $form->field($model, 'disadvantages') ?>
    <?= $form->field($model, 'crossgender') ?>
    <?= $form->field($model, 'why') ?>
    <?= $form->field($model, 'video') ?>
    <?= $form->field($model, 'foto') ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- member-register -->

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>
<div class="header-title">
    <div class="vertical-center">
        Восстановление пароля
    </div>
</div>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>



    <div class="main-box main-custom" style="min-height: calc(100% - 237px);">
        <div class="container text-center">
            <p>Пожалуйста, введите свой e-mail для получения ссылки восстановления.</p>
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form', 'options' => ['class' => 'form'], 'fieldConfig' => ['template' => '{input}']]); ?>

                <?= $form
                    ->field($model, 'email', ['template' => '{error}{input}<i class="fa fa-envelope"></i>'])
                    ->input('email', ['autofocus' => true,'placeholder' => "E-mail"])
                    ->error(['tag'=>'div'])?>


                <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>
<div class="header-title">
    <div class="vertical-center">
        Смена пароля
    </div>
</div>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Новый пароль:</p>

    <div class="main-box main-custom" style="min-height: calc(100% - 237px);">
        <div class="container text-center">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form', 'options' => ['class' => 'form'], 'fieldConfig' => ['template' => '{input}']]); ?>

                <?= $form->field($model, 'password', ['template' => '<div class="form-group">{input}<i class="fa fa-lock"></i></div>'])->passwordInput(['autofocus' => true]) ?>
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = "Регистрация";

$this->registerJs('
jQuery(document.body).on("click", "#captcha-refresh", function(e) {
    jQuery("#signupform-captcha-image").yiiCaptcha("refresh");
    return false;
});
jQuery(document.body).on("click.yiiCaptcha", "#signupform-captcha-image", function(e) {
    e.preventDefault();
    console.log("asd");
    return false;
});
');

?>
<div class="header-title">
    <div class="vertical-center">РЕГИСТРАЦИЯ</div>
</div>
<div class="main-box main-custom">
    <div class="container text-center">
        <?php $form = ActiveForm::begin(['id' => 'form-signup', 'validationUrl'=> Url::to(['/site/signupvalidate']), 'enableAjaxValidation' => true, 'options' => ['class' => 'form']]); ?>
            <?= $form
                ->field($model, 'username', ['template' => '{error}{input}<i class="fa fa-user"></i>'])
                ->textInput(['placeholder' => "Никнейм (Логин)"])
                ->error(['tag'=>'div'])?>
                
            <?= $form
                ->field($model, 'password', ['template' => '{error}{input}<i class="fa fa-lock"></i>'])
                ->passwordInput(['placeholder' => "Пароль"])
                ->error(['tag'=>'div'])?>

            <?= $form
                ->field($model, 'password_conf', ['template' => '{error}{input}<i class="fa fa-lock"></i>'])
                ->passwordInput(['placeholder' => "Подтверждение пароля"])
                ->error(['tag'=>'div'])?>

            <?= $form
                ->field($model, 'email', ['template' => '{error}{input}<i class="fa fa-envelope"></i>'])
                ->input('email', ['placeholder' => "E-mail"])
                ->error(['tag'=>'div'])?>

            <?= \yii\captcha\Captcha::widget([
                    'model' => $model,
                    'attribute'=>'captcha',
                    'imageOptions' => ['class' => 'captcha-img', 'width' => '136px', 'height' => '43px'],
                    'options' => ['showRefreshButton' => false],
                    'value' => 'form-control vissible-390',
                    'template' => '{image}<a href="#" id="captcha-refresh" class="captcha-refresh"><i class="fa fa-refresh captcha-refresh"></i></a>'
            ])?>

            <?= $form
                ->field($model, 'captcha', ['options' => ['class'=>'form-group captcha-code'], 'template' => '{error}{input}'])
                ->textInput(['class'=>'form-control hidden-390','placeholder' => "Код с картинки"])
                ->error(['tag'=>'div'])?>
            
            <ul class="text-left check-wrapper">
                <li>
                    <?= $form
                        ->field($model, 'license_check', ['options'=> ['wrapper'=>false]])
                        ->checkbox(['template'=>'{error}{input}{beginLabel}{labelTitle}{endLabel}'])
                        ->label('Я принимаю условия <a href="#" class="page-link">Соглашения</a>')
                    ?>
                </li>
                <li class="empty"></li>
                <li>
                    <?= $form
                        ->field($model, 'subscribe_news', ['options'=> ['wrapper'=>false]])
                        ->checkbox(['template'=>'{input}{beginLabel}{labelTitle}{endLabel}'])
                        ->label('Новости? Мне интересно!')
                    ?>
                </li>
                <li class="empty"></li>
            </ul>
            <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>


        <?php ActiveForm::end(); ?>
    </div>
</div>